import { PrismaClient, Category } from '@prisma/client';

interface ArticleSeedData {
  title: string;
  slug: string;
  content: string;
  category: Category;
  coverImage: string;
}

const ARTICLES_DATA: ArticleSeedData[] = [
  {
    title: 'Jamie Siddons Appointed Head Coach of Sri Lanka Women’s Team',
    slug: 'jamie-siddons-appointed-head-coach-of-sri-lanka-womens-team',
    content:
      'Sri Lanka Cricket has announced the appointment of former Australian cricketer Jamie Siddons as the new Head Coach of the Sri Lanka National Women’s Team. The one-year contract will take effect on 16 March 2026, positioning Siddons to lead the team through a crucial period of development and international competition. His first major assignment will be guiding the side during the Sri Lanka Women’s Tour of Bangladesh in April–May 2026, followed by preparations for the prestigious ICC Women’s T20 World Cup 2026 in England this June. This appointment comes at a pivotal moment for Sri Lankan women’s cricket, which has shown remarkable progress in recent years but still seeks consistency against top-tier nations.\n\n' +
      'Siddons brings a wealth of experience to the role, having previously served as Head Coach of the Bangladesh National Men’s Team from 2007 to 2011 — his highest-profile international coaching stint where he helped transform the Tigers into a competitive force in both Test and limited-overs cricket. A Level 3 qualified coach accredited by Cricket Australia, he also led the South Australia Cricket Team (Redbacks) from 2015 to 2020, achieving back-to-back Sheffield Shield finals appearances, and the Wellington Firebirds in New Zealand from 2011 to 2015, where he focused on developing young talent into international stars. Before transitioning to coaching, Siddons enjoyed a successful first-class career in Australia, captaining both South Australia and Victoria and scoring over 12,000 runs across all formats. His deep understanding of Asian conditions, tactical acumen, and player-management skills make him an ideal fit for the Sri Lankan setup.\n\n' +
      'In an exclusive statement released by Sri Lanka Cricket, Siddons expressed his excitement: “I am honoured to join the Sri Lanka Women’s Team at this exciting stage. The players have immense talent and potential, and I look forward to working closely with them to build a cohesive unit that can compete at the highest level. My focus will be on fitness, mental conditioning, and smart cricket strategies that leverage the team’s natural flair.” Sri Lanka Cricket officials believe Siddons’ proven track record at international and domestic levels will help elevate the women’s team’s performance on the global stage. With the T20 World Cup on the horizon, the focus will be on building a cohesive unit capable of competing against the world’s best. The board has already allocated an additional LKR 150 million for specialized training camps, video analysis systems, and overseas exposure tours to Australia and England.\n\n' +
      'Recent encouraging performances, such as clinching the ODI series against West Indies 2-1 despite a final-match loss in February 2026, have boosted morale. Players like Chamari Athapaththu and Inoka Ranaweera have publicly welcomed the appointment, with Athapaththu stating in a press conference, “Jamie’s experience will help us take the next step. We are ready to learn and grow under his guidance.” Analysts from ESPNcricinfo and Cricbuzz have praised the move, noting that Siddons’ emphasis on data-driven decisions and youth integration could mirror the success he achieved with Bangladesh. Fans across the country, from Colombo to Jaffna, have taken to social media to express optimism, with hashtags like #SiddonsSLWomen trending nationally.\n\n' +
      'This strategic appointment not only injects fresh expertise and tactical acumen into the women’s setup but also signals Sri Lanka Cricket’s commitment to gender equality in the sport. The federation plans to integrate the women’s team more closely with the men’s high-performance centre in Khettarama, allowing shared access to physiotherapists, nutritionists, and sports psychologists. Looking ahead, Siddons is expected to introduce modern training methodologies, including virtual reality simulations for match scenarios and advanced biomechanics for injury prevention. With the T20 World Cup just months away, the entire nation is rallying behind the team, hoping this new chapter under Jamie Siddons will finally deliver the global breakthrough Sri Lankan women’s cricket has long deserved. The appointment marks the beginning of a new era of professionalism, strategic depth, and sustained success across all formats of the game.',
    category: Category.SPORTS,
    coverImage: 'https://picsum.photos/seed/sports-cricket-women-coach/800/400',
  },
  {
    title:
      'Colombo Stock Exchange Forges Strategic Partnership with NSEIX to Expand Capital Market Access',
    slug: 'colombo-stock-exchange-forges-strategic-partnership-with-nseix-to-expand-capital-market-access',
    content:
      'The Colombo Stock Exchange (CSE) has entered into a strategic partnership with NSEIX, marking a significant step towards broadening access to capital markets and enhancing investment opportunities across Sri Lanka. Announced on 6 March 2026, the collaboration aims to facilitate greater participation from both local and international investors, creating new avenues for capital flow and market growth. This move comes at a time when the CSE continues to show resilience, with the All Share Price Index (ASPI) recently climbing to 22,834 points on 5 March — a 1.74% daily gain that underscores growing investor confidence amid broader economic stabilization following years of turbulence.\n\n' +
      'The partnership will introduce cutting-edge trading platforms, cross-border settlement mechanisms, and joint investment products that align with global standards. NSEIX, a leading international exchange operator known for its innovative solutions in emerging markets, will provide technical expertise and training to CSE staff while opening doors for Sri Lankan companies to list on international platforms. Complementing this development, Capital Alliance has deepened its footprint in the capital markets by listing its third closed-end fund on the CSE earlier in February 2026, attracting over LKR 2.5 billion in subscriptions from retail and institutional investors alike.\n\n' +
      'These initiatives reflect a concerted push to strengthen Sri Lanka’s financial ecosystem, building on positive economic indicators such as a 33% surge in worker remittances to US$729 million in February 2026 and a steady increase in foreign reserves to over US$6 billion. Analysts from Fitch Ratings and Moody’s have noted that improved foreign reserves, successful debt restructuring under the IMF Extended Fund Facility, and government fiscal reforms have created a more attractive environment for investment. Key sectors like banking, manufacturing, tourism, and renewable energy are driving recent momentum, with banking stocks alone contributing 28% to the ASPI’s year-to-date gains.\n\n' +
      'The partnership with NSEIX is expected to introduce innovative products such as exchange-traded funds focused on Sri Lankan green bonds, improved trading mechanisms including algorithmic trading capabilities, and expanded market linkages that will benefit retail investors, institutions, and SMEs alike. Local brokerage houses have already begun offering educational webinars to prepare investors for the new opportunities, while international fund managers from Singapore and Dubai have expressed interest in allocating fresh capital to Sri Lankan blue-chip companies. As Sri Lanka’s economy continues its recovery trajectory, these capital market advancements signal strong potential for sustained growth and position the CSE as a more dynamic player in the regional financial landscape.\n\n' +
      'Investors are closely watching how these developments translate into increased liquidity and long-term value creation for the market. The CSE chairman, in a detailed press briefing, highlighted that the collaboration could boost daily trading volumes by 40% within the first year and attract an additional US$500 million in foreign portfolio investment by the end of 2026. With inflation stabilized at 4.2% and interest rates trending downward, the timing could not be better for both domestic and foreign participants. This landmark partnership not only enhances market access but also reinforces Sri Lanka’s commitment to transparent, technology-driven capital markets that foster inclusive economic growth for all citizens.',
    category: Category.BUSINESS,
    coverImage: 'https://picsum.photos/seed/business-stock-partnership/800/400',
  },
  {
    title:
      'Sri Lankan Documentary on Economic Crisis Wins Best Social Film and Screenplay at Indian Festival',
    slug: 'sri-lankan-documentary-on-economic-crisis-wins-best-social-film-and-screenplay-at-indian-festival',
    content:
      'In a major boost for Sri Lankan cinema, the Pulitzer Center-supported documentary *Democracy in Debt: Sri Lanka Beyond the Headlines* has been awarded ‘Best Social Film’ and ‘Best Screenplay’ at the Second Jalgaon International Film Festival in India. The awards will be presented on 1 March 2026 at the Abdul Kalam Azad Research Centre in Aurangabad, Maharashtra, with winners receiving a trophy, certificate, and traditional Maharashtra pagri. The film was selected from over 2,500 submissions from 75 countries, with only 250 entries chosen by an international jury comprising professionals from India, Iran, Egypt, Portugal, and the Netherlands. This double victory marks the first time a Sri Lankan production has claimed top honours in both categories at this prestigious event.\n\n' +
      'Produced by Boston-based Pakistani journalist and filmmaker Beena Sarwar in collaboration with Sri Lankan historian and filmmaker Sinha Raja Tammita Delgoda (who served as co-director, co-scriptwriter, special consultant, and project conceptualizer) and researcher Uditha Devapriya, the documentary explores the social and political dimensions of Sri Lanka’s economic crisis that peaked in 2022. It features in-depth interviews with protestors from the Aragalaya movement, economists, farmers affected by the organic fertilizer policy, and ordinary citizens who lost savings and livelihoods. The film premiered privately at the Barberyn Ayurveda resort in Weligama in July 2024, followed by a high-profile Colombo cinema premiere hosted by Factum International.\n\n' +
      'Since its debut, the documentary has been screened at over 80 events across 25 countries on five continents, including prestigious venues such as Emerson College and Cornell University in the United States, as well as packed auditoriums in Karachi, Lahore, New Delhi, Dhaka, and Kathmandu. Audience feedback has been overwhelmingly positive, with many viewers describing it as a “powerful testament to resilience and the fight for democratic accountability.” The film’s screenplay, praised for its nuanced storytelling that avoids sensationalism while highlighting systemic failures, was particularly lauded by the jury for its balanced portrayal of complex issues.\n\n' +
      'This recognition highlights the global relevance of Sri Lankan storytelling and the power of independent cinema to address pressing national issues. As the first production under the Southasia Peace Action Network and Sapan News, the documentary underscores the importance of cross-border collaboration in documenting democratic and economic challenges. Festival director Anil Deshmukh stated, “The Sri Lankan entry stood out for its raw honesty and cinematic excellence. It has sparked important conversations that transcend borders.” The awards not only celebrate the film’s artistic excellence but also amplify Sri Lanka’s voice on the international stage, paving the way for greater visibility of local talent and thought-provoking narratives in global film circles.\n\n' +
      'Following the win, the producers announced plans for a nationwide theatrical release in Sri Lanka in April 2026 and a special screening at the Colombo International Film Festival. Streaming platforms in India and Pakistan have already expressed interest in acquiring rights, while educational institutions in Sri Lanka are planning to incorporate the film into media and political science curricula. The success of *Democracy in Debt* serves as an inspiring reminder that even in times of crisis, Sri Lankan creatives can produce world-class work that resonates far beyond national boundaries and contributes to global discourse on governance, economic justice, and human rights.',
    category: Category.ENTERTAINMENT,
    coverImage:
      'https://picsum.photos/seed/entertainment-documentary-awards/800/400',
  },
  {
    title:
      'AI-Driven Entrepreneurship Will Transform Sri Lanka’s Economy, Says Deputy Minister',
    slug: 'ai-driven-entrepreneurship-will-transform-sri-lankas-economy-says-deputy-minister',
    content:
      'Sri Lanka’s economic future lies in AI-powered entrepreneurship, according to Deputy Minister of Digital Economy Eng. Eranga Weeraratne. Speaking as Chief Guest at the ITAM–32 International Conference organized by the University of Vavuniya on 26 February 2026 under the theme “Technology-Based Entrepreneurship for Inclusive Growth in the AI Era,” the Deputy Minister outlined a bold vision for leveraging artificial intelligence to drive national transformation. He emphasized that the global economy is undergoing a massive shift centered on AI, where data functions as capital and innovation serves as the primary currency. The conference, attended by over 800 delegates from 12 countries, featured panel discussions on ethical AI, startup funding, and rural digital inclusion.\n\n' +
      'Weeraratne stressed the need to move beyond traditional small and medium enterprises by encouraging startups that harness modern technologies such as cloud computing, data analytics, and machine learning. He compared AI’s transformative potential to that of electricity or the internet, noting its direct applications in healthcare (medical diagnostics and telemedicine), agriculture (precision farming and crop yield prediction), finance (digital payments and fraud detection), and public services (improved efficiency in tax collection and disaster management). As a developing nation, Sri Lanka has a unique opportunity to “leapfrog” traditional development stages and accelerate progress through responsible AI adoption. The government is prioritizing data infrastructure — akin to roads and ports — alongside robust cybersecurity measures, ethical AI frameworks, and responsible data governance policies.\n\n' +
      'Addressing concerns about job displacement from automation, the Deputy Minister highlighted the importance of upskilling the workforce through enhanced digital literacy programs and lifelong learning initiatives. He underscored the government’s commitment to reducing the urban-rural digital divide by expanding affordable broadband to all 25 districts and introducing digital financial systems that reach even the most remote villages. “National progress should not be measured solely by GDP growth, but also by the extent to which technology improves the quality of life of the people,” he stated. Concrete steps already underway include the launch of the National AI Innovation Hub in Colombo with an initial investment of LKR 500 million and partnerships with global tech leaders like Google and Microsoft for training 50,000 youth by 2028.\n\n' +
      'The conference also featured success stories from local startups such as an AI-powered agritech platform that increased farmer incomes by 45% in the North Central Province and a fintech company using machine learning to provide micro-loans to women entrepreneurs in the estate sector. International speakers from India’s NASSCOM and Singapore’s Smart Nation initiative praised Sri Lanka’s proactive approach. Deputy Minister Weeraratne concluded his address by announcing a new AI Entrepreneurship Fund worth LKR 2 billion, offering grants and low-interest loans to promising startups. This forward-looking strategy positions Sri Lanka to build an inclusive digital economy where innovation benefits every segment of society, from urban professionals to rural farmers and youth in conflict-affected areas.\n\n' +
      'Experts predict that widespread AI adoption could add up to 3.5% to Sri Lanka’s annual GDP growth by 2030, creating over 200,000 new jobs in tech-related fields while enhancing productivity across traditional sectors. The government has also committed to establishing regulatory sandboxes for AI experimentation and collaborating with universities to integrate AI curricula at undergraduate level. With these comprehensive measures, Sri Lanka is poised to emerge as a regional leader in responsible AI-driven entrepreneurship, ensuring that technological advancement translates into tangible improvements in living standards and economic resilience for all citizens.',
    category: Category.TECHNOLOGY,
    coverImage: 'https://picsum.photos/seed/tech-ai-entrepreneurship/800/400',
  },
  {
    title:
      'Sri Lanka Parliament Scraps Lawmaker Pensions in Landmark Reform to Cut Politician Perks',
    slug: 'sri-lanka-parliament-scraps-lawmaker-pensions-in-landmark-reform-to-cut-politician-perks',
    content:
      'In a historic move to reduce privileges for politicians, Sri Lanka’s Parliament has abolished pensions for all legislators and their widows. The 225-member legislature, where the ruling party holds a two-thirds majority, passed the repeal of the 49-year-old Parliamentary Pensions Act on Tuesday with 154 votes in favour and only two against. Justice Minister Harsana Nanayakkara justified the decision by stating, “When people see the quality of debate and what members say in this House, they don’t think MPs deserve a pension.” The reform has been hailed as a major step towards restoring public trust after years of economic hardship and political discontent.\n\n' +
      'The landmark legislation aligns with the leftist government’s pledge under President Anura Kumara Dissanayake to prune excessive perks enjoyed by politicians. It follows the recent withdrawal of housing, luxury vehicles, fuel allowances, secretarial staff, and thousands of bodyguards from former presidents — a process accelerated after former President Mahinda Rajapaksa refused to vacate a state bungalow in 2025. In 2021, Rajapaksa reportedly spent around 800 million rupees refurbishing a government residence, drawing widespread criticism. Similar privileges previously extended to Gotabaya Rajapaksa were also curtailed after his 2022 resignation amid economic turmoil and mass protests.\n\n' +
      'Opposition Leader Sajith Premadasa objected to the move during the debate, arguing that a pension provides necessary social security and prevents lawmakers from turning to corruption for retirement security. Under the old law, MPs qualified for pensions after just five years in office — half the requirement for ordinary state employees — and the maximum pension could reach 75% of salary. The changes mark a significant step towards greater accountability and fiscal responsibility, with estimated savings of over LKR 1.2 billion annually redirected to public health and education. Many observers view this as part of a broader effort to restore public trust in governance, especially in the wake of the country’s recent economic crisis that led to sovereign debt default in 2022.\n\n' +
      'Civil society groups and trade unions have welcomed the reform, organizing street celebrations in Colombo and Kandy. Transparency International Sri Lanka issued a statement praising the move as “a long-overdue correction that puts people before politicians.” The repeal takes immediate effect and is expected to set a precedent for further reforms in political entitlements, including potential limits on foreign travel and staff allowances. President Dissanayake, in a televised address, promised additional measures such as asset declaration reforms and independent oversight of parliamentary expenses.\n\n' +
      'The decision has sparked nationwide debate on social media and in local media outlets, with many citizens expressing hope that it signals a new era of clean politics. Economists have calculated that the cumulative cost of politician pensions since 1977 exceeded LKR 15 billion, funds that could have been used for critical infrastructure. As Sri Lanka continues its journey towards economic recovery under the IMF program, this bold reform demonstrates the government’s willingness to lead by example and prioritize fiscal discipline. The entire nation will be watching closely to see how this precedent influences future political culture and public service delivery across the island.',
    category: Category.POLITICS,
    coverImage: 'https://picsum.photos/seed/politics-pensions-reform/800/400',
  },
  {
    title:
      'Sri Lanka Under-19 Cricket Team Qualifies for World Cup Finals with Thrilling Victory',
    slug: 'sri-lanka-under-19-cricket-team-qualifies-for-world-cup-finals-with-thrilling-victory',
    content:
      'In a sensational display of talent and resilience, Sri Lanka’s Under-19 cricket team has qualified for the finals of the ICC Under-19 Cricket World Cup 2026 after a thrilling 12-run victory over arch-rivals India in the semi-final played at the iconic R. Premadasa Stadium in Colombo on 8 March 2026. Chasing a challenging target of 248, the Indian side fell short despite a valiant 87 from captain Adarsh Singh, thanks to a heroic spell of 4 for 32 by Sri Lankan left-arm spinner Malsha Madushanka. The win sends the island nation into the final against Australia, scheduled for 12 March at the same venue, marking the first time Sri Lanka has reached the Under-19 World Cup final since 2000.\n\n' +
      'The match was a rollercoaster of emotions, with Sri Lanka posting 247 for 7 in 50 overs after being put in to bat. Opener Pulindu Perera top-scored with 68, while middle-order batsman Dinura Kalupahana contributed a crucial 54. India fought back strongly in the middle overs, but Sri Lanka’s death bowling, led by fast bowler Vishwa Fernando Jr., proved decisive. Head coach Chandika Hathurusingha praised the team’s composure under pressure, saying, “These boys showed true Sri Lankan fighting spirit. They believed in themselves and executed the plans perfectly.” The victory triggered massive celebrations across the country, with fans gathering in public spaces from Galle to Jaffna to watch the match on giant screens.\n\n' +
      'This achievement comes after a strong group stage campaign where Sri Lanka remained unbeaten, defeating strong sides like England and Bangladesh. The team’s success is attributed to a revamped youth development program initiated by Sri Lanka Cricket in 2024, which includes state-of-the-art training facilities in Pallekele and regular exposure tours to Australia and South Africa. Talent scouts have identified over 150 promising players from rural areas, ensuring the squad represents the diversity of the nation. The final against Australia promises to be a classic encounter, with both teams boasting world-class pace attacks and spin options.\n\n' +
      'Sports analysts predict that a win in the final could inspire a new generation of cricketers and boost investment in grassroots cricket. The government has already announced a special incentive package of LKR 10 million for the squad if they lift the trophy. President Anura Kumara Dissanayake congratulated the team via social media, stating, “This is a proud moment for every Sri Lankan. Your dedication and unity reflect the best of our nation.” With millions expected to tune in for the final, the Under-19 team has united the country in a wave of patriotism and hope. The journey to the final has already produced several future stars, and the entire cricket fraternity is confident that this young squad will bring home the coveted title and write a new chapter in Sri Lankan cricket history.',
    category: Category.SPORTS,
    coverImage:
      'https://picsum.photos/seed/sports-u19-cricket-world-cup/800/400',
  },
  {
    title:
      'Sri Lankan Rupee Strengthens Against US Dollar Amid Positive Economic Indicators',
    slug: 'sri-lankan-rupee-strengthens-against-us-dollar-amid-positive-economic-indicators',
    content:
      'The Sri Lankan Rupee has strengthened significantly against the US Dollar, reaching a four-month high of LKR 292.50 per dollar on 7 March 2026, driven by robust economic indicators and increased foreign inflows. This marks a 3.8% appreciation since the beginning of the year and reflects growing confidence in the government’s reform agenda under the IMF-supported program. Central Bank Governor Dr. Nandalal Weerasinghe attributed the gains to a 28% rise in export earnings, particularly from apparel and tea sectors, combined with a record inflow of remittances exceeding US$780 million in February alone.\n\n' +
      'Foreign reserves have climbed to US$6.8 billion, providing a comfortable buffer for debt servicing and essential imports. Tourism arrivals have also rebounded strongly, with over 180,000 visitors in February 2026 — a 45% increase year-on-year — injecting much-needed foreign exchange. The Central Bank has maintained a stable policy rate at 8.5%, balancing growth and inflation which currently stands at a manageable 4.1%. These positive developments have encouraged foreign portfolio investors to return, with net inflows into the Colombo Stock Exchange crossing US$120 million in the first quarter.\n\n' +
      'Economists from the Asian Development Bank and World Bank have revised upward their growth forecasts for Sri Lanka to 4.8% for 2026, citing improved macroeconomic stability and structural reforms in taxation and public enterprises. The government’s decision to accelerate digitalization of customs and introduce a single-window trade platform has further boosted investor sentiment. Local manufacturers in the free trade zones of Katunayake and Biyagama have reported increased orders from European and American buyers, contributing to the rupee’s strength.\n\n' +
      'The Central Bank has warned against excessive speculation and vowed to intervene if necessary to maintain orderly market conditions. Finance Minister Ravi Karunanayake stated in Parliament, “This strengthening is the result of disciplined policies and collective efforts of all Sri Lankans. We remain committed to sustainable growth that benefits every citizen.” Banks have begun offering more attractive rates on foreign currency deposits, encouraging expatriates to remit more funds through formal channels. As the rupee continues to appreciate, importers of raw materials are experiencing reduced costs, which is expected to ease pressure on consumer prices and support small businesses across the island.\n\n' +
      'Looking ahead, analysts predict further stabilization if political stability is maintained and key infrastructure projects such as the Colombo Port City expansion proceed smoothly. The positive momentum has also attracted interest from sovereign wealth funds in the Middle East and Asia for long-term investments in renewable energy and technology sectors. This strengthening of the rupee is not merely a currency movement but a tangible sign of Sri Lanka’s economic resurgence, offering renewed hope to millions who endured severe hardships during the 2022 crisis. The coming months will be crucial as the country works towards achieving upper-middle-income status through prudent fiscal management and inclusive growth strategies.',
    category: Category.BUSINESS,
    coverImage: 'https://picsum.photos/seed/business-rupee-strength/800/400',
  },
  {
    title:
      'Popular Sri Lankan Actor Launches New Web Series on Local Streaming Platform',
    slug: 'popular-sri-lankan-actor-launches-new-web-series-on-local-streaming-platform',
    content:
      'Renowned Sri Lankan actor and producer Jackson Anthony has launched his much-anticipated web series *Shadows of the Lotus* exclusively on the homegrown streaming platform SriFlix on 5 March 2026. The eight-episode psychological thriller, set in the scenic hills of Nuwara Eliya during the colonial era, explores themes of love, betrayal, and social inequality through the eyes of a young tea plantation worker. Within the first 48 hours of release, the series has already garnered over 1.2 million views, making it the fastest-growing original content in SriFlix history and signaling a new era for local digital entertainment.\n\n' +
      'Jackson Anthony, who also directs and stars in the lead role, invested over LKR 180 million in production, employing more than 250 local crew members and utilizing state-of-the-art drones for breathtaking aerial shots of tea estates and misty mountains. The cast includes rising stars like Senuri Ranathunga and veteran actress Iranganie Serasinghe, whose powerful performances have been widely praised by critics. The series features an original soundtrack composed by legendary musician Rohana Weerasinghe, blending traditional Sinhala folk melodies with modern electronic elements to create an immersive auditory experience.\n\n' +
      'SriFlix CEO Tharindu Perera revealed that the platform’s subscriber base has grown by 65% since the launch, reaching 2.8 million users island-wide. The series is available in Sinhala with English and Tamil subtitles, ensuring accessibility across diverse communities. Early reviews from local film critics have been overwhelmingly positive, with the Daily Mirror describing it as “a masterpiece that captures the soul of Sri Lanka while delivering universal appeal.” International platforms such as Netflix have reportedly approached the producers for global distribution rights.\n\n' +
      'The launch event held at the BMICH in Colombo was attended by prominent figures from the arts, politics, and business sectors, including Minister of Cultural Affairs. Jackson Anthony, in his speech, emphasized the importance of supporting local talent and stories. “This series is not just entertainment; it is a celebration of our rich heritage and a call to reflect on the issues that still shape our society today,” he said. The production also incorporated sustainable practices, using eco-friendly sets and partnering with local communities for location permissions.\n\n' +
      'The success of *Shadows of the Lotus* is expected to encourage more investors to fund high-quality Sri Lankan web content, creating thousands of jobs in the creative industry. Streaming platforms are now planning to increase budgets for original productions, aiming to position Sri Lanka as a regional hub for digital storytelling in South Asia. Fans have flooded social media with theories about the plot twists and praise for the authentic portrayal of colonial-era life. As the series continues to trend, it is clear that Sri Lankan entertainment is entering a golden digital age, driven by visionary artists and supportive technology infrastructure.',
    category: Category.ENTERTAINMENT,
    coverImage:
      'https://picsum.photos/seed/entertainment-web-series-launch/800/400',
  },
  {
    title:
      'Sri Lanka’s First 5G Network Rollout Begins in Colombo and Major Cities',
    slug: 'sri-lankas-first-5g-network-rollout-begins-in-colombo-and-major-cities',
    content:
      'Sri Lanka has officially begun the rollout of its first 5G network, with Dialog Axiata and Mobitel simultaneously activating ultra-high-speed services in Colombo, Kandy, and Galle on 8 March 2026. The milestone was marked by a live demonstration at the Presidential Secretariat where President Anura Kumara Dissanayake made the first 5G video call to the Mayor of Kandy. Download speeds exceeding 1.2 Gbps were recorded during the event, promising to revolutionize connectivity, business operations, and daily life across the island.\n\n' +
      'The government has allocated LKR 45 billion through the Digital Economy Framework to support the nationwide expansion, with full coverage targeted for all provincial capitals by December 2026 and rural areas by 2028. Dialog Axiata has invested US$180 million in new base stations and spectrum acquisition, while Mobitel partnered with Ericsson for advanced equipment. Early users in Colombo report seamless streaming of 8K videos, instant cloud backups, and lag-free online gaming, transforming how professionals work remotely and students access educational resources.\n\n' +
      'The 5G rollout is expected to create over 15,000 direct and indirect jobs in installation, maintenance, and application development. Key sectors poised to benefit include telemedicine in rural hospitals, precision agriculture for farmers using drone monitoring, and smart traffic management in congested cities. The Ministry of Digital Economy has launched a nationwide training program to upskill 25,000 youth in 5G-related technologies, ensuring no one is left behind in the digital revolution.\n\n' +
      'International technology experts from South Korea and Singapore have hailed the rapid progress, noting that Sri Lanka has leapfrogged several stages compared to many developing nations. Security protocols aligned with global standards have been implemented to protect user data and critical infrastructure. President Dissanayake stated, “5G is not just about faster internet; it is about creating opportunities, improving healthcare, and building a smarter, more inclusive Sri Lanka.”\n\n' +
      'As the network expands, local startups are already developing 5G-powered solutions such as real-time translation apps for tourists and AI-based disaster warning systems. The rollout has also attracted foreign direct investment, with several multinational companies announcing plans to establish regional data centres in Sri Lanka. This technological leap positions the country as a competitive player in the global digital economy, promising higher productivity, better services, and a brighter future for the next generation of Sri Lankans.',
    category: Category.TECHNOLOGY,
    coverImage: 'https://picsum.photos/seed/tech-5g-rollout/800/400',
  },
  {
    title: 'President Dissanayake Announces New Anti-Corruption Task Force',
    slug: 'president-dissanayake-announces-new-anti-corruption-task-force',
    content:
      'President Anura Kumara Dissanayake has announced the formation of a powerful new Anti-Corruption Task Force (ACTF) during a special address to the nation on 7 March 2026. The independent body, comprising retired judges, forensic accountants, and international experts from Transparency International, will have sweeping powers to investigate and prosecute corruption cases involving public officials, politicians, and private entities linked to government contracts. The move is part of the government’s broader commitment to good governance and has been welcomed by civil society as a decisive step towards eradicating systemic corruption that plagued the nation for decades.\n\n' +
      'The task force will operate with a dedicated budget of LKR 850 million and full autonomy from political interference, reporting directly to Parliament through a bipartisan oversight committee. Initial focus areas include probing high-value public procurement deals from 2015 to 2024, recovery of stolen assets stashed overseas, and digitization of all government tenders to minimize human discretion. President Dissanayake emphasized, “Corruption is the biggest obstacle to our economic recovery. This task force will ensure that every rupee stolen from the people is recovered and those responsible are held accountable, regardless of their position.”\n\n' +
      'The announcement comes amid growing public demand for justice following the economic crisis of 2022. The ACTF has already received over 1,200 complaints in its first 24 hours through a secure online portal and hotline. International partners, including the World Bank and European Union, have pledged technical assistance and training for investigators. Legal experts predict that the new body could recover assets worth billions of rupees within the first year of operation.\n\n' +
      'Opposition parties have expressed cautious support while calling for transparency in the selection of task force members. Civil society organizations have organized awareness campaigns to educate citizens on reporting mechanisms. The task force is also mandated to recommend legislative reforms, including stronger whistleblower protection and asset declaration laws for all public servants. As Sri Lanka continues its journey towards sustainable development under the IMF program, the establishment of the ACTF sends a clear message that accountability and transparency will form the foundation of the new Sri Lanka.\n\n' +
      'The initiative has received positive coverage in international media, boosting investor confidence and reinforcing the country’s image as a nation serious about reform. With strong public backing and robust institutional support, the Anti-Corruption Task Force is poised to become a cornerstone of good governance, paving the way for a fairer, more prosperous future for all Sri Lankans.',
    category: Category.POLITICS,
    coverImage: 'https://picsum.photos/seed/politics-anti-corruption/800/400',
  },
  {
    title:
      'Sri Lanka Records Significant Drop in Dengue Cases Due to New Mosquito Control Program',
    slug: 'sri-lanka-records-significant-drop-in-dengue-cases-due-to-new-mosquito-control-program',
    content:
      'Sri Lanka has achieved a remarkable 68% reduction in dengue fever cases during the first two months of 2026 compared to the same period last year, thanks to the successful implementation of a comprehensive National Mosquito Control Program launched in November 2025. The Ministry of Health reported only 1,245 confirmed cases nationwide in January and February, with zero deaths — a stark contrast to the 3,892 cases and 12 fatalities recorded in early 2025. Health authorities attribute the dramatic decline to innovative biological control methods, community participation, and advanced surveillance technology.\n\n' +
      'The program introduced Wolbachia-infected mosquitoes in high-risk areas, a safe and environmentally friendly technique that prevents dengue transmission by altering the breeding capabilities of Aedes mosquitoes. Over 12 million such mosquitoes have been released in Colombo, Gampaha, and Kandy districts with support from the World Health Organization and Australian scientists. Additionally, the government distributed more than 850,000 long-lasting insecticide-treated nets and conducted weekly fogging and source reduction drives involving 25,000 public health inspectors and community volunteers.\n\n' +
      'Advanced GIS mapping and drone surveillance have enabled rapid identification and elimination of breeding sites, particularly in urban slums and rural agricultural areas. Public awareness campaigns using social media, television, and school programs have reached over 18 million citizens, encouraging everyone to eliminate stagnant water weekly. Schools across the country have integrated dengue prevention into their curricula, with students participating in monthly clean-up drives.\n\n' +
      'Health Minister Dr. Nalinda Jayatissa praised the collective effort, stating, “This success demonstrates what we can achieve when science, community action, and government commitment work together. We are on track to make Sri Lanka dengue-free by 2028.” Hospitals have reported a significant decrease in admissions, freeing up resources for other critical healthcare needs. International experts from the WHO have described Sri Lanka’s approach as a model for other tropical nations facing similar challenges.\n\n' +
      'The program’s success has boosted tourism confidence, with visitors reassured by the low disease risk. The government plans to expand the initiative to all 25 districts and invest an additional LKR 1.2 billion in 2026 for vaccine research partnerships. As dengue cases continue to decline, Sri Lanka is emerging as a regional leader in vector-borne disease control, improving public health outcomes and quality of life for millions of citizens while setting a benchmark for sustainable healthcare innovation in the developing world.',
    category: Category.HEALTH,
    coverImage: 'https://picsum.photos/seed/health-dengue-control/800/400',
  },
  {
    title:
      'Indian Premier League 2026: Sri Lankan Players Shine in Opening Matches',
    slug: 'indian-premier-league-2026-sri-lankan-players-shine-in-opening-matches',
    content:
      'Sri Lankan cricketers have made a stellar start to the Indian Premier League (IPL) 2026 season, with several players delivering match-winning performances in the opening week of the world’s most lucrative T20 franchise tournament. Wanindu Hasaranga, playing for Royal Challengers Bengaluru, claimed a five-wicket haul for just 18 runs against Chennai Super Kings on 6 March, earning the Player of the Match award and setting the tournament alight. Meanwhile, Matheesha Pathirana of Chennai Super Kings took 4 wickets in his first two games, reinforcing his reputation as one of the most feared death bowlers in the league.\n\n' +
      'The strong showing by Sri Lankan talent has been widely celebrated back home, with millions tuning in via live broadcasts on local television and streaming platforms. Hasaranga’s performance not only boosted his franchise’s campaign but also increased his market value ahead of the next auction. Pathirana’s express pace and pinpoint yorkers have drawn comparisons to legendary Sri Lankan pacers Lasith Malinga and Chaminda Vaas. Other Sri Lankans, including Charith Asalanka and Maheesh Theekshana, have also contributed crucial cameos and economical spells, proving the depth of talent emerging from the island nation.\n\n' +
      'IPL franchises have invested heavily in Sri Lankan players this season, spending over US$28 million collectively during the mega auction in December 2025. The success of these athletes is expected to inspire thousands of young cricketers in Sri Lanka and strengthen bilateral ties between the two cricket-mad nations. The Board of Control for Cricket in India (BCCI) and Sri Lanka Cricket have announced joint training camps to further develop skills exchange programs. Fans in Colombo and rural areas have organized viewing parties, turning every Sri Lankan player’s success into a national celebration.\n\n' +
      'Sports commentators predict that continued strong performances could lead to more Sri Lankans securing captaincy roles and high-value contracts in future seasons. The IPL’s global platform continues to provide invaluable exposure and financial rewards, helping players support their families while elevating the standard of Sri Lankan cricket. As the tournament progresses through March and April, the entire country will be cheering for these stars, hoping their brilliance on the grand stage translates into future success for the national team in international competitions.',
    category: Category.SPORTS,
    coverImage:
      'https://picsum.photos/seed/sports-ipl-sri-lankan-players/800/400',
  },
  {
    title:
      'Foreign Direct Investment in Sri Lanka Surges 25% in First Quarter of 2026',
    slug: 'foreign-direct-investment-in-sri-lanka-surges-25-in-first-quarter-of-2026',
    content:
      'Foreign Direct Investment (FDI) into Sri Lanka has surged by 25% in the first quarter of 2026, reaching US$612 million according to the Board of Investment (BOI) latest figures released on 8 March. Major inflows have come from renewable energy projects in the Northern Province, technology parks in the Western Province, and tourism infrastructure developments along the Southern coast. This significant increase reflects growing international confidence in Sri Lanka’s economic reforms, political stability, and improved ease of doing business ranking.\n\n' +
      'Key investors include companies from China, India, Singapore, and the United Arab Emirates, with notable projects such as a 150 MW solar power plant in Mannar and a state-of-the-art data centre in Katunayake. The BOI has approved 42 new projects worth over US$1.2 billion, creating an estimated 8,500 direct jobs. The government’s streamlined approval process, single-window clearance system, and tax incentives introduced in the 2025 Budget have played a crucial role in attracting these investments.\n\n' +
      'The tourism sector alone attracted US$185 million, with new resort developments in Arugam Bay and Passikudah promising to boost visitor numbers to 3 million by year-end. Technology and manufacturing sectors followed closely, with several European firms establishing garment and electronics assembly plants that emphasize sustainable practices. The Central Bank has noted that these FDI inflows have contributed to the strengthening of foreign reserves and the appreciation of the Sri Lankan Rupee.\n\n' +
      'BOI Chairman Sanjeewa Gunawardana stated, “This surge is a direct result of the trust investors have placed in our transparent policies and the hard work of our people. We are committed to maintaining this momentum through further digitalization and infrastructure development.” International rating agencies have upgraded Sri Lanka’s outlook to positive, citing reduced political risk and successful debt restructuring. As the country continues to implement structural reforms, FDI is projected to exceed US$2.5 billion for the full year, supporting sustainable economic growth and creating opportunities for local entrepreneurs and skilled workers.\n\n' +
      'The positive trend has also encouraged Sri Lankan diaspora communities in Australia, the UK, and Canada to explore investment opportunities back home, further strengthening economic ties. With continued focus on green energy, digital infrastructure, and human capital development, Sri Lanka is well-positioned to become a preferred investment destination in South Asia, delivering long-term prosperity for current and future generations.',
    category: Category.BUSINESS,
    coverImage: 'https://picsum.photos/seed/business-fdi-surge/800/400',
  },
  {
    title:
      'Sri Lankan Film ‘The Whispering Palms’ Nominated for International Award in Cannes',
    slug: 'sri-lankan-film-the-whispering-palms-nominated-for-international-award-in-cannes',
    content:
      'The critically acclaimed Sri Lankan film *The Whispering Palms*, directed by acclaimed filmmaker Vimukthi Jayasundara, has been officially nominated for the prestigious Palme d’Or at the 79th Cannes Film Festival to be held in May 2026. This marks the first time in over a decade that a Sri Lankan production has received such high-level international recognition. The film, which premiered at the Busan International Film Festival in October 2025, tells the poignant story of a young woman navigating tradition and modernity in a coastal fishing village in southern Sri Lanka.\n\n' +
      'Shot entirely on location in Hambantota and Galle with a cast of local actors and non-professionals, the movie features breathtaking cinematography of pristine beaches, lush palm groves, and vibrant village life. The script, written by Jayasundara himself, explores themes of environmental conservation, gender roles, and cultural identity with subtle yet powerful storytelling. Lead actress Anjali Perera has already received widespread praise for her nuanced performance, earning her a special mention at the Asian Film Awards earlier this year.\n\n' +
      'The nomination has generated immense excitement within Sri Lanka’s film community and among the general public. The National Film Corporation has announced special screenings across the island, while the Ministry of Cultural Affairs plans to host a red-carpet send-off event for the cast and crew in Colombo. International critics have described the film as “a visual poem that captures the soul of Sri Lanka” and “a masterful blend of realism and lyricism.”\n\n' +
      'Director Jayasundara, who previously won the Caméra d’Or at Cannes in 2005 for his debut feature, expressed gratitude: “This nomination belongs to every Sri Lankan who believes in the power of cinema to tell our stories to the world. I hope *The Whispering Palms* inspires more young filmmakers to pursue their dreams.” The festival selection committee highlighted the film’s universal appeal and technical excellence among 1,800 submissions from around the globe.\n\n' +
      'The recognition is expected to open new doors for Sri Lankan cinema on the global stage, attracting co-production offers and distribution deals. Streaming giants have already shown interest in acquiring rights, while tourism authorities anticipate increased visitors to the filming locations. As the countdown to Cannes begins, the entire nation is rallying behind *The Whispering Palms*, celebrating this proud achievement that showcases Sri Lanka’s rich artistic talent and cultural heritage to the world.',
    category: Category.ENTERTAINMENT,
    coverImage:
      'https://picsum.photos/seed/entertainment-cannes-nomination/800/400',
  },
  {
    title: 'Global Tech Giants Eye Sri Lanka for AI Research Hubs',
    slug: 'global-tech-giants-eye-sri-lanka-for-ai-research-hubs',
    content:
      'Major global technology companies including Google, Microsoft, and IBM have expressed strong interest in establishing Artificial Intelligence research and development hubs in Sri Lanka, according to announcements made during the International Tech Summit held in Colombo on 6 March 2026. Senior executives from these firms met with President Anura Kumara Dissanayake and the Minister of Digital Economy to discuss potential investments exceeding US$450 million over the next three years. The move is driven by Sri Lanka’s young, tech-savvy population, competitive talent costs, and improving digital infrastructure.\n\n' +
      'Google has proposed a dedicated AI ethics and language processing centre in Kandy, focusing on developing solutions for Sinhala and Tamil languages to benefit regional markets. Microsoft plans to set up a cloud and AI innovation lab in Colombo, while IBM is exploring a quantum computing research facility in partnership with local universities. These hubs are expected to create over 4,000 high-skilled jobs and provide training opportunities for thousands more students through scholarship programs.\n\n' +
      'The government has offered attractive incentives, including tax holidays, streamlined visa processes for foreign experts, and access to high-speed 5G networks. The University of Moratuwa and University of Colombo have already signed memoranda of understanding to supply talent and research facilities. Local startups will gain access to cutting-edge tools and mentorship from global experts, accelerating innovation in sectors such as healthcare diagnostics, agricultural optimization, and financial technology.\n\n' +
      'Deputy Minister Eranga Weeraratne described the development as “a game-changer that will position Sri Lanka as South Asia’s AI innovation hub.” International analysts have noted that the country’s strategic location, political stability, and English-speaking workforce make it an ideal destination compared to other emerging markets. The first facilities are scheduled to open by September 2026, with full operations by 2028.\n\n' +
      'This influx of global tech investment is expected to boost the digital economy, enhance export revenues from IT services, and foster a culture of research and entrepreneurship. As Sri Lanka embraces the AI revolution, these partnerships will not only drive economic growth but also ensure that the benefits of advanced technology reach every corner of the island, empowering the next generation to compete on the global stage.',
    category: Category.TECHNOLOGY,
    coverImage: 'https://picsum.photos/seed/tech-ai-hubs/800/400',
  },
  {
    title:
      'EU Parliament Passes Resolution Supporting Sri Lanka’s Debt Restructuring Efforts',
    slug: 'eu-parliament-passes-resolution-supporting-sri-lankas-debt-restructuring-efforts',
    content:
      'The European Union Parliament has overwhelmingly passed a resolution on 7 March 2026 expressing strong support for Sri Lanka’s ongoing debt restructuring process and commending the country’s progress towards economic stability. The non-binding but politically significant resolution, adopted by a vote of 478 in favour to 92 against, calls on EU member states to accelerate bilateral debt negotiations and provide additional technical assistance to Sri Lanka. This development is expected to facilitate smoother discussions with remaining creditors and boost international confidence in the island nation’s recovery trajectory.\n\n' +
      'The resolution highlights Sri Lanka’s successful completion of the first review under the IMF Extended Fund Facility, the implementation of comprehensive tax reforms, and the reduction of the fiscal deficit to 5.5% of GDP. It also praises the government’s commitment to anti-corruption measures and social protection programs that have cushioned the impact of economic reforms on vulnerable populations. Members of the European Parliament from across political groups spoke in support, emphasizing the importance of a stable Sri Lanka for regional security and trade in the Indian Ocean.\n\n' +
      'Sri Lankan Foreign Minister Vijitha Herath welcomed the resolution during a press conference in Colombo, stating, “This strong endorsement from the EU Parliament reinforces our reform agenda and will help unlock further concessional financing and investment.” The European Union is one of Sri Lanka’s largest trading partners and development cooperation providers, with annual trade exceeding €4 billion and development aid focused on green energy, education, and governance.\n\n' +
      'The resolution urges the EU Commission to explore new trade preferences under the GSP+ scheme and to support Sri Lanka’s efforts to diversify its economy through sustainable tourism and technology exports. Analysts believe the positive signal will encourage other bilateral creditors, including Japan and India, to finalize agreements in the coming months. As Sri Lanka continues its journey from crisis to recovery, this international backing from the European Union provides both moral and practical encouragement, strengthening the nation’s resolve to build a resilient and inclusive economy for all citizens.\n\n' +
      'The development has been widely covered in European media and has already led to increased inquiries from European investors interested in Sri Lankan infrastructure and renewable energy projects. With continued support from global partners, Sri Lanka is well on its way to achieving sustainable growth and regaining its position as a vibrant economy in the region.',
    category: Category.POLITICS,
    coverImage: 'https://picsum.photos/seed/politics-eu-resolution/800/400',
  },
];

export async function seedArticles(
  prisma: PrismaClient,
  authorId: string,
): Promise<void> {
  if (!authorId) {
    console.log('   No author ID provided. Skipping article seeding.');
    return;
  }

  console.log('\n Seeding articles...');

  for (const articleData of ARTICLES_DATA) {
    const article = await prisma.article.upsert({
      where: { slug: articleData.slug },
      update: {},
      create: {
        title: articleData.title,
        slug: articleData.slug,
        content: articleData.content,
        category: articleData.category,
        coverImage: articleData.coverImage,
        published: true,
        publishedAt: new Date(),
        authorId,
      },
    });

    console.log(`   Article: "${article.title}" [${article.category}]`);
  }

  console.log(`Articles seeding completed. Total: ${ARTICLES_DATA.length}`);
}
