export const APP_CONSTANTS = {
  DEFAULT_PORT: 8000,
  MAX_PORT_ATTEMPTS: 10,
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 12,
  MAX_LIMIT: 100,
  DEFAULT_FRONTEND_URL: 'http://localhost:3000',
  DEFAULT_JWT_EXPIRATION: '1h',
  SWAGGER_TITLE: 'News Platform API',
  SWAGGER_DESCRIPTION: 'News platform REST API',
  SWAGGER_VERSION: '1.0',
  SWAGGER_PATH: 'api/docs',
};
